sudo: true

env:
  - RSPEC_TAG=integration
  - RSPEC_TAG="~integration"

#matrix:
#  include:
#    - env: RSPEC_TAG=integration
#    - env: RSPEC_TAG=~integration

language: ruby
rvm:
  - 2.2.0

git:
  submodules: false

addons:
  apt:
    packages:
      - valgrind
      - check
      - pkg-config
      - gcc

before_install:
  # Update to latest bundler
  - gem update --system
  - gem --version
  - wget -qO- http://testmycode.net/travis/2.2.0-tmc-server-bundler-cache.tar.gz | tar xz
  - BUNDLE_GEMFILE=Gemfile bundle install --retry=3 --jobs=3 --deployment
  # Reduce mavens memory usage
  - export MAVEN_OPTS="-Xms512m -Xmx1024m -XX:PermSize=1024m"
  # So that travis can clone submodules
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  - git config --global user.email "travis@example.com"
  - git config --global user.name "Travis"
  # tmc-check
  - export CHECK_INSTALL_DIR=$HOME/check
  - mkdir $CHECK_INSTALL_DIR
  - git clone https://github.com/testmycode/tmc-check.git
  - cd tmc-check
  - env BUNDLE_GEMFILE=$(pwd)/Gemfile bundle install --jobs=3 --retry=3 --deployment
  - env BUNDLE_GEMFILE=$(pwd)/Gemfile make
  - env BUNDLE_GEMFILE=$(pwd)/Gemfile make install PREFIX=$CHECK_INSTALL_DIR BUNDLE_GEMFILE="$(pwd)/Gemfile"
  - export PATH="$CHECK_INSTALL_DIR/bin:$PATH"
  - cd ..
  - export LD_LIBRARY_PATH=$CHECK_INSTALL_DIR/lib:/lib:/usr/lib:/usr/local/lib:$LD_LIBRARY_PATH
  - export C_INCLUDE_PATH=$CHECK_INSTALL_DIR/include:$C_INCLUDE_PATH
  - export PKG_CONFIG_PATH=$CHECK_INSTALL_DIR/lib/pkgconfig:$PKG_CONFIG_PATH
  #tmc comet, compile manually since rake task keeps on failing in travis...
  - cd ext/tmc-comet/
  - mvn install -q -Dmaven.test.skip=true
  - cd ../../
  # Build submodule deps
  - BUNDLE_GEMFILE=Gemfile bundle exec rake compile
  # use prebuilt tmc-sandbox
  - wget -qO- http://testmycode.net/travis/sandbox-$(git submodule status ext/tmc-sandbox | grep -E -o  "[0-9a-f]{40}").tar.gz | tar xvz -C ext/
  - cd ext/tmc-sandbox/web

  - sed -i "s/ tmc/ $(whoami)/" site.defaults.yml
  - sed -i '/^network:$/{$!{N;s/^network:\n  enabled: true$/network:\n  enabled: false/;ty;P;D;:y}}' site.defaults.yml
  - cat site.defaults.yml
  - BUNDLE_GEMFILE=$(pwd)/Gemfile bundle install --retry=3 --jobs=3
  - BUNDLE_GEMFILE=$(pwd)/Gemfile rake ext
  - cd ../../../

install:
  - echo $(pwd)
  - BUNDLE_GEMFILE=Gemfile bundle install --retry=3 --jobs=3 --deployment

services:
  - postgresql

before_script:
  - createuser -U postgres -s tmc
  - bundle exec rake db:reset
  - export rvmsudo_secure_path=1

script:
  - BUNDLE_GEMFILE=$(pwd)/ext/tmc-sandbox/web/Gemfile ./ext/tmc-sandbox/web/webapp.rb start
  - BUNDLE_GEMFILE=$(pwd)/ext/tmc-sandbox/web/Gemfile ./ext/tmc-sandbox/web/webapp.rb status
  - sleep 10
  - BUNDLE_GEMFILE=$(pwd)/ext/tmc-sandbox/web/Gemfile ./ext/tmc-sandbox/web/webapp.rb status
  - curl 127.0.0.1:3001
  - curl -v 127.0.0.1:3001/status.json
  - bundle exec rake spec SPEC_OPTS="--tag $RSPEC_TAG --tag ~network -f d" LD_LIBRARY_PATH=$CHECK_INSTALL_DIR/lib:/lib:/usr/lib:/usr/local/lib:$LD_LIBRARY_PATH C_INCLUDE_PATH=$CHECK_INSTALL_DIR/include:$C_INCLUDE_PATH PKG_CONFIG_PATH=$CHECK_INSTALL_DIR/lib/pkgconfig:$PKG_CONFIG_PATH SANDBOX_HOST=127.0.0.1 SANDBOX_PORT=3001
  - cat ext/tmc-sandbox/web/log/*


before_cache:
  - mkdir -p sandbox-cache && SANDBOX=$(git submodule status ext/tmc-sandbox | grep -E -o  "[0-9a-f]{40}") && mkdir -p sandbox-cache/$SANDBOX && cp ext/tmc-sandbox/uml/{linux.uml,initrd.img,rootfs.squashfs} sandbox-cache/$SANDBOX_HOST

