sudo: true

language: ruby
rvm:
  - 2.2.0

git:
  submodules: false

addons:
  apt:
    packages:
      - valgrind
      - check
      - pkg-config
      - gcc

before_install:
  - gem update --system
  - gem --version
  - BUNDLE_GEMFILE=Gemfile bundle install --retry=3 --jobs=3 --deployment
  - export MAVEN_OPTS="-Xms512m -Xmx1024m -XX:PermSize=1024m"
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  - git config --global user.email "travis@example.com"
  - git config --global user.name "Travis"
  # tmc-check
  - mkdir $HOME/check
  - git clone https://github.com/testmycode/tmc-check.git
  - cd tmc-check
  - env BUNDLE_GEMFILE=$(pwd)/Gemfile bundle install --jobs=3 --retry=3
  - env BUNDLE_GEMFILE=$(pwd)/Gemfile make
  - env BUNDLE_GEMFILE=$(pwd)/Gemfile make install PREFIX=$HOME/check BUNDLE_GEMFILE="$(pwd)/Gemfile"
  - export PATH="$HOME/check/bin:$PATH"
  - cd ..
  - export LD_LIBRARY_PATH=$HOME/check/lib:/lib:/usr/lib:/usr/local/lib:$LD_LIBRARY_PATH
  - export C_INCLUDE_PATH=$HOME/check/include:$C_INCLUDE_PATH
  - export PKG_CONFIG_PATH=$HOME/check/lib/pkgconfig:$PKG_CONFIG_PATH
    #tmc comet, compile manually...
  - cd ext/tmc-comet/
  - mvn install -q -Dmaven.test.skip=true
  - cd ../../
  # use prebuilt tmc-sandbox
  - rm -rf ext/tmc-sandbox
  - wget -qO- http://testmycode.net/prebuild-sandbox/sandbox.tar.gz | sudo tar xz -C ext/
  - cd ext/tmc-sandbox/web
  - ls -la .
  - sudo cp ../../../.sandbox-site.travis.yml site.yml
  - sudo sed -i "s/ tmc/ $(whoami)/" site.yml
  - BUNDLE_GEMFILE=$(pwd)/Gemfile rvmsudo bundle install --retry=3 --jobs=3
  - BUNDLE_GEMFILE=$(pwd)/Gemfile rvmsudo rake ext
  - cd ../../../
  - sudo patch ext/tmc-sandbox/web/webapp.rb 0001-Fix-running-with-network-disabled.patch

install:
  - echo $(pwd)
  - BUNDLE_GEMFILE=Gemfile bundle install --retry=3 --jobs=3 --deployment
  - BUNDLE_GEMFILE=Gemfile bundle exec rake compile

services:
  - postgresql

before_script:
  - createuser -U postgres -s tmc
  - bundle exec rake db:reset
  - export rvmsudo_secure_path=1

script:
  - BUNDLE_GEMFILE=$(pwd)/ext/tmc-sandbox/web/Gemfile rvmsudo ext/tmc-sandbox/web/webapp.rb start
  - BUNDLE_GEMFILE=$(pwd)/ext/tmc-sandbox/web/Gemfile rvmsudo ext/tmc-sandbox/web/webapp.rb status
  - sleep 10
  - BUNDLE_GEMFILE=$(pwd)/ext/tmc-sandbox/web/Gemfile rvmsudo ext/tmc-sandbox/web/webapp.rb status
  - curl 127.0.0.1:3001
  - curl -v 127.0.0.1:3001/status.json
  - rvmsudo bundle exec rake spec SPEC="spec/integration" SPEC_OPTS="-f d" LD_LIBRARY_PATH=$HOME/check/lib:/lib:/usr/lib:/usr/local/lib:$LD_LIBRARY_PATH C_INCLUDE_PATH=$HOME/check/include:$C_INCLUDE_PATH PKG_CONFIG_PATH=$HOME/check/lib/pkgconfig:$PKG_CONFIG_PATH SANDBOX_HOST=127.0.0.1 SANDBOX_PORT=3001
  - cat ext/tmc-sandbox/web/log/*
  - df -h
  - rvmsudo bundle exec rake spec SPEC_OPTS="-f d" LD_LIBRARY_PATH=$HOME/check/lib:/lib:/usr/lib:/usr/local/lib:$LD_LIBRARY_PATH C_INCLUDE_PATH=$HOME/check/include:$C_INCLUDE_PATH PKG_CONFIG_PATH=$HOME/check/lib/pkgconfig:$PKG_CONFIG_PATH SANDBOX_HOST=127.0.0.1 SANDBOX_PORT=3001
  - cat ext/tmc-sandbox/web/log/*
  - df -h
