sudo: true

language: ruby
rvm:
  - 2.2.0

git:
  submodules: false

addons:
  apt:
    packages:
      - build-essential

before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  - git config --global user.email "travis@example.com"
  - git config --global user.name "Travis"
  - rm -rf ext/tmc-sandbox
  - wget -qO- http://testmycode.net/prebuild-sandbox/sandbox.tar.gz | sudo tar xz -C ext/
  - cd ext/tmc-sandbox/web && ls -la . && sed -i 's/\: tmc/\: $(whoami)/' site.default.yml && BUNDLE_GEMFILE=$(pwd)/Gemfile bundle install && BUNDLE_GEMFILE=$(pwd)/Gemfile rvmsudo rake ext && cd ../../../
  - cd ext/tmc-sandbox/uml && sudo ./run-test-exercise.sh && cd ../../../

services:
  - postgresql

before_script:
  - createuser -U postgres -s tmc
  - bundle exec rake db:reset
  - export rvmsudo_secure_path=1

script:
  - rvmsudo bundle exec rake spec SPEC="spec/integration"
