sudo: true

language: ruby
rvm:
  - 2.2.0

git:
  submodules: false

addons:
  apt:
    packages:
      - valgrind
      - check
      - pkg-config
      - gcc
      - maven


before_install:
  - sudo ip tuntap add dev tap_tmc0 mode tap user travis.
  - BUNDLE_GEMFILE=Gemfile bundle install --retry=3 --deployment
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  - git config --global user.email "travis@example.com"
  - git config --global user.name "Travis"
  # tmc-check
  - mkdir $HOME/check
  - git clone https://github.com/testmycode/tmc-check.git
  - cd tmc-check
  - env BUNDLE_GEMFILE=$(pwd)/Gemfile bundle install --jobs=3 --retry=3
  - env BUNDLE_GEMFILE=$(pwd)/Gemfile make
  - env BUNDLE_GEMFILE=$(pwd)/Gemfile make install PREFIX=$HOME/check BUNDLE_GEMFILE="$(pwd)/Gemfile"
  - export PATH="$HOME/check/bin:$PATH"
  - cd ..
  - export LD_LIBRARY_PATH=$HOME/check/lib:/lib:/usr/lib:/usr/local/lib:$LD_LIBRARY_PATH
  - export C_INCLUDE_PATH=$HOME/check/include:$C_INCLUDE_PATH
  - export PKG_CONFIG_PATH=$HOME/check/lib/pkgconfig:$PKG_CONFIG_PATH
  # use prebuilt tmc-sandbox
  - rm -rf ext/tmc-sandbox
  - wget -qO- http://testmycode.net/prebuild-sandbox/sandbox.tar.gz | sudo tar xz -C ext/
  - cd ext/tmc-sandbox/web
  - ls -la .
  - sudo sed -i "s/ tmc/ $(whoami)/" site.defaults.yml
  - BUNDLE_GEMFILE=$(pwd)/Gemfile rvmsudo bundle install --retry=3 --jobs=3
  - BUNDLE_GEMFILE=$(pwd)/Gemfile rvmsudo rake ext
  - cd ../../../
  - cd ext/tmc-sandbox/uml
  - sudo ./run-test-exercise.sh
  - cd ../../../
  - sudo mkdir -p /home/tmc/build/tmc-sandbox/misc/squidroot
  - sudo mount --bind "$(pwd)/ext/tmc-sandbox/misc/squidroot" /home/tmc/build/tmc-sandbox/misc/squidroot
  - mount
  - rvmsudo ./ext/tmc-sandbox/web/webapp.rb run

install:
  - echo $(pwd)
  - rake compile
  - BUNDLE_GEMFILE=Gemfile bundle install --retry=3 --deployment

services:
  - postgresql

before_script:
  - createuser -U postgres -s tmc
  - bundle exec rake db:reset
  - export rvmsudo_secure_path=1

script:
  - rvmsudo bundle exec rake spec SPEC="spec/integration" SPEC_OPTS="--fail-fast" LD_LIBRARY_PATH=$HOME/check/lib:/lib:/usr/lib:/usr/local/lib:$LD_LIBRARY_PATH C_INCLUDE_PATH=$HOME/check/include:$C_INCLUDE_PATH PKG_CONFIG_PATH=$HOME/check/lib/pkgconfig:$PKG_CONFIG_PATH
  - cat ext/tmc-sandbox/web/log/*
  - rvmsudo bundle exec rake spec SPEC="spec/integration"
